name: Branch Check

on: 
  pull_request:
    branches: 
      - master

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        run: |
          if [[ "${{ github.head_ref }}" != "develop" ]]; then
            echo "Only PRs from 'develop' branch are allowed to merge into 'master'."
            exit 1
          fi

